# Generated by Django 4.2.1 on 2023-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_weather_clothing', models.ImageField(upload_to='images')),
                ('hot_weather_clothing', models.ImageField(upload_to='images')),
            ],
        ),
    ]
